-- ANIMAL_INS에서 ANIMAL_ID, NAME을 추출한다.
-- A,B 각 두 테이블을 ID 기준으로 묶어준다. (LEFT JOIN 사용)
-- DATETIME이 들어온 시간보다 나간 시간이 더 빠른 경우를 찾는다.
SELECT AINS.ANIMAL_ID, AINS.NAME
FROM ANIMAL_INS AINS
LEFT JOIN ANIMAL_OUTS AOUTS
ON AINS.ANIMAL_ID = AOUTS.ANIMAL_ID
WHERE AINS.DATETIME > AOUTS.DATETIME
ORDER BY AINS.DATETIME