-- TYPE이 DATETIME인 데이터에서 시간을 추출 : HOUR(DATETIME)
-- 조회 결과의 열의 이름을 HOUR로 설정 : HOUR(DATETIME) HOUR
SELECT HOUR(DATETIME) HOUR, COUNT(DATETIME) COUNT
FROM ANIMAL_OUTS
where HOUR(DATETIME) >= 9 and HOUR(DATETIME) <= 19
group by HOUR(DATETIME)
order by HOUR(DATETIME)